name: Tests CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          #npm-version: ''
      - run: npm install
      - run: npm run test:scripts
