name: Tests CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test build scripts and run unit tests
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: yarn add --dev jest-junit
      - uses: IgnusG/jest-report-action@v2.3.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run test:scripts
      - run: npm run test-unit
