name: Tests CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test build scripts and run unit tests
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
#      - run: npm run test:scripts
      - run: npm run test-unit
      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        args: >
          -Dsonar.organization=goodarit
          -Dsonar.projectKey=goodari_brave-core
          -Dsonar.sources=components/brave_new_tab_ui/containers/
          -Dsonar.test.exclusions=components/test/brave_new_tab_ui/containers/**
          -Dsonar.tests=components/test/brave_new_tab_ui/containers/
          -Dsonar.verbose=true
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
